### ISSUE TITLE
Restructering

### ISSUE THREAD

**Issue by dschuermann** [free-software-for-android/ad-away#657]
@0-kaladin Hi,
I wasn't able to contact you via other channels: I needed to do some restructurings of my Android projects. So don't be confused that I AdAway is now under a different Github organization. Nothing actually changes :P

**Comment by 0-kaladin** [comment]
No problem. Can use 0.kaladin@gmail whenever you need.

**Comment by dschuermann** [comment]
I invited you to a new team, please accept :)

**Comment by 0-kaladin** [comment]
all set, thanks.
